### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by WillDawnlll** [FOrmyown/Alesense-Antivirus#1]
love the ui design and operational logic
Can you recommend some relevant information to me?
Some books or web resources about antivirus drivers
Can you talk about what is the knowledge system needed to complete this as?
thank  you  ，@v@

**Comment by Formyown** [comment]
that is actually based on a DUI engine called Bolt http://bolt.xunlei.com/ 
and there are three greate books about windows driver development _天书夜读, 寒江独钓_ and _竹林溪径_
for the knowledge about antivirus technology, reading the _恶意代码分析实战（Practical malware analysis）_ is a good choice

**Comment by WillDawnlll** [comment]
谢谢！

**Comment by WillDawnlll** [comment]
中文书名。。。老哥是华人！?

**Comment by Formyown** [comment]
是啊
